alias la='eza -lhaG --no-user --sort type'
alias ls='la'
alias cla='clear && la'
alias nvim='nvim -p'
alias icat='kitten icat'
alias ytm='systemd-inhibit --what=sleep:idle --who="ytm-player" --why="IM BLASTIN DEM BEATS" --mode="block-weak" ytm'
