alias ls='eza -lah --no-filesize --no-time --no-user --sort type'
alias la='eza -lhaguU --follow-symlinks --sort type'
alias cla='clear && la'
alias nvim='nvim -p'
alias icat='kitten icat'
alias ytm='systemd-inhibit --what=sleep:idle --who="ytm-player" --why="IM BLASTIN DEM BEATS" --mode="block" ytm'
